name: tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5

      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u golang.org/x/lint/golint
          make test-coverage
      - name: Upload test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test_coverage_report
          path: coverage.html
